version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:24-jdk

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Set up Gradle
          command: |
            mkdir -p ~/.gradle
            echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - run:
          name: Build with Gradle
          command: ./gradlew build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
